# Generated by Django 2.2.3 on 2019-07-20 13:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnumber', models.IntegerField(unique=True)),
                ('projectname', models.TextField()),
                ('engineering_start', models.DateField(blank=True, null=True)),
                ('Mechanical_Release', models.DateField(blank=True, null=True)),
                ('Electrical_Release', models.DateField(blank=True, null=True)),
                ('Manufacturing', models.DateField(blank=True, null=True)),
                ('Finishing', models.DateField(blank=True, null=True)),
                ('Assembly', models.DateField(blank=True, null=True)),
                ('Integration', models.DateField(blank=True, null=True)),
                ('Internal_Runoff', models.DateField(blank=True, null=True)),
                ('Customer_Runoff', models.DateField(blank=True, null=True)),
                ('Ship', models.DateField(blank=True, null=True)),
                ('Install_Start', models.DateField(blank=True, null=True)),
                ('Install_Finish', models.DateField(blank=True, null=True)),
                ('Documentation', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update')], default='offtrack', max_length=20, null=True)),
                ('iscurrent', models.BooleanField(default=True, null=True)),
                ('lastupdated', models.DateField(default=datetime.datetime(2015, 10, 21, 0, 0), null=True)),
                ('projectmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InitialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnumber', models.IntegerField()),
                ('projectname', models.CharField(max_length=100)),
                ('Mechanical_Release', models.DateField(null=True)),
                ('Electrical_Release', models.DateField(null=True)),
                ('Manufacturing', models.DateField(null=True)),
                ('Finishing', models.DateField(null=True)),
                ('Assembly', models.DateField(null=True)),
                ('Integration', models.DateField(null=True)),
                ('Internal_Runoff', models.DateField(null=True)),
                ('Customer_Runoff', models.DateField(null=True)),
                ('Ship', models.DateField(null=True)),
                ('Install_Start', models.DateField(null=True)),
                ('Install_Finish', models.DateField(null=True)),
                ('Documentation', models.DateField(null=True)),
                ('Status', models.CharField(choices=[('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update')], default='offtrack', max_length=20, null=True)),
                ('iscurrent', models.BooleanField(default=True, null=True)),
                ('lastupdated', models.DateField(default=datetime.datetime(2015, 10, 21, 0, 0), null=True)),
                ('projectmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
