# Generated by Django 2.1.4 on 2019-06-16 17:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnumber', models.IntegerField()),
                ('projectname', models.CharField(max_length=100)),
                ('Mechanical_Release', models.DateField(null=True)),
                ('Electrical_Release', models.DateField(null=True)),
                ('Manufacturing', models.DateField(null=True)),
                ('Finishing', models.DateField(null=True)),
                ('Assembly', models.DateField(null=True)),
                ('Integration', models.DateField(null=True)),
                ('Internal_Runoff', models.DateField(null=True)),
                ('Customer_Runoff', models.DateField(null=True)),
                ('Ship', models.DateField(null=True)),
                ('Install_Start', models.DateField(null=True)),
                ('Install_Finish', models.DateField(null=True)),
                ('Documentation', models.DateField(null=True)),
                ('offtrack', models.BooleanField(null=True)),
                ('onwatch', models.BooleanField(null=True)),
                ('iscurrent', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnumber', models.IntegerField()),
                ('projectname', models.CharField(max_length=100)),
                ('engineering_start', models.DateField(blank=True, null=True)),
                ('Mechanical_Release', models.DateField(blank=True, null=True)),
                ('mechanicalreleasecomplete', models.BooleanField(default=False)),
                ('Electrical_Release', models.DateField(blank=True, null=True)),
                ('electricalreleasecomplete', models.BooleanField(default=False)),
                ('Manufacturing', models.DateField(blank=True, null=True)),
                ('manufacturingcomplete', models.BooleanField(default=False)),
                ('Finishing', models.DateField(blank=True, null=True)),
                ('finishingcomplete', models.BooleanField(default=False)),
                ('Assembly', models.DateField(blank=True, null=True)),
                ('assemblycomplete', models.BooleanField(default=False)),
                ('Integration', models.DateField(blank=True, null=True)),
                ('integrationcomplete', models.BooleanField(default=False)),
                ('Internal_Runoff', models.DateField(blank=True, null=True)),
                ('internalrunoffcomplete', models.BooleanField(default=False)),
                ('Customer_Runoff', models.DateField(blank=True, null=True)),
                ('customerrunoffcomplete', models.BooleanField(default=False)),
                ('Ship', models.DateField(blank=True, null=True)),
                ('shipcomplete', models.BooleanField(default=False)),
                ('Install_Start', models.DateField(blank=True, null=True)),
                ('installstartcomplete', models.BooleanField(default=False)),
                ('Install_Finish', models.DateField(blank=True, null=True)),
                ('installfinishcomplete', models.BooleanField(default=False)),
                ('Documentation', models.DateField(blank=True, null=True)),
                ('documentationcomplete', models.BooleanField(default=False)),
                ('offtrack', models.BooleanField(default=True, null=True)),
                ('onwatch', models.BooleanField(default=True, null=True)),
                ('iscurrent', models.BooleanField(default=True, null=True)),
                ('lastupdated', models.DateField(default=datetime.datetime(2015, 10, 21, 0, 0), null=True)),
                ('projectmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
