# Generated by Django 2.1.4 on 2019-07-14 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialproject',
            name='Status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update')], default='offtrack', max_length=10, null=True), size=None),
        ),
    ]
