# Generated by Django 2.2.3 on 2019-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Summary',
            field=models.CharField(default='No update.', max_length=30, null=True),
        ),
    ]
