# Generated by Django 2.1.4 on 2019-04-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
