# Generated by Django 2.1.4 on 2019-04-12 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_projectmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectmanager',
        ),
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
