# Generated by Django 2.1.4 on 2019-06-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190616_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assemblycomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customerrunoffcomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentationcomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='electricalreleasecomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='finishingcomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='installfinishcomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='installstartcomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='integrationcomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='internalrunoffcomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manufacturingcomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mechanicalreleasecomplete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='shipcomplete',
        ),
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update')], default='OT', max_length=10),
        ),
    ]
