# Generated by Django 2.1.4 on 2019-04-13 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20190412_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectmanager',
        ),
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
