# Generated by Django 2.1.4 on 2019-07-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190715_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialproject',
            name='Status',
            field=models.CharField(choices=[('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update')], default='offtrack', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update')], default='offtrack', max_length=20, null=True),
        ),
    ]
