# Generated by Django 2.1.4 on 2019-01-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190120_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ontrack',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='onwatch',
            field=models.BooleanField(null=True),
        ),
    ]
