# Generated by Django 2.1.4 on 2019-04-14 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190413_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lastupdated',
            field=models.DateField(default=datetime.datetime(2019, 10, 21, 0, 0), null=True),
        ),
    ]
