# Generated by Django 2.2.3 on 2019-07-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190720_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Summary',
            new_name='Comments',
        ),
    ]
