# Generated by Django 2.1.4 on 2019-07-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190630_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialproject',
            name='projectnumber',
            field=models.IntegerField(help_text="Acieta's Project Number Format - 4 digits + 00"),
        ),
    ]
