# Generated by Django 2.1.4 on 2019-07-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190715_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialproject',
            name='Status',
            field=models.CharField(choices=[('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update'), ('ontrack', 'On Track')], default='offtrack', max_length=20, null=True),
        ),
    ]
