# Generated by Django 2.1.4 on 2019-01-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190126_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ontrack',
            new_name='offtrack',
        ),
    ]
