# Generated by Django 2.1.4 on 2019-04-14 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lastupdated',
            field=models.DateField(default=datetime.datetime(2015, 10, 21, 0, 0), null=True),
        ),
    ]
