# Generated by Django 2.1.4 on 2019-07-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190716_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialproject',
            name='Status',
            field=models.CharField(choices=[('ontrack', 'On Track'), ('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update')], default='offtrack', max_length=20, null=True),
        ),
    ]
