# Generated by Django 2.2.3 on 2019-08-09 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190721_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Electrical_Release',
            field=models.DateField(blank=True, null=True, verbose_name='Electrical Release'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Mechanical_Release',
            field=models.DateField(blank=True, null=True, verbose_name='Mech Rel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
