# Generated by Django 2.2.3 on 2019-08-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190809_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Integration',
        ),
    ]
