# Generated by Django 2.1.4 on 2019-04-19 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190414_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assembly',
            new_name='Assembly',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='customerrunoff',
            new_name='Customer_Runoff',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='documentation',
            new_name='Documentation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='electricalrelease',
            new_name='Electrical_Release',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='finishing',
            new_name='Finishing',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='installfinish',
            new_name='Install_Finish',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='installstart',
            new_name='Install_Start',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='integration',
            new_name='Integration',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='internalrunoff',
            new_name='Internal_Runoff',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='manufacturing',
            new_name='Manufacturing',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='mechanicalrelease',
            new_name='Mechanical_Release',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ship',
            new_name='Ship',
        ),
    ]
