# Generated by Django 2.1.4 on 2019-01-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190126_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnumber', models.IntegerField()),
                ('projectname', models.CharField(max_length=100)),
                ('mechanicalrelease', models.DateField(null=True)),
                ('electricalrelease', models.DateField(null=True)),
                ('manufacturing', models.DateField(null=True)),
                ('finishing', models.DateField(null=True)),
                ('assembly', models.DateField(null=True)),
                ('integration', models.DateField(null=True)),
                ('internalrunoff', models.DateField(null=True)),
                ('customerrunoff', models.DateField(null=True)),
                ('ship', models.DateField(null=True)),
                ('installstart', models.DateField(null=True)),
                ('installfinish', models.DateField(null=True)),
                ('documentation', models.DateField(null=True)),
                ('offtrack', models.BooleanField(null=True)),
                ('onwatch', models.BooleanField(null=True)),
                ('employees', models.ManyToManyField(to='projects.Employee')),
            ],
        ),
    ]
