# Generated by Django 2.2.3 on 2019-08-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('offtrack', 'Off Track'), ('onwatch', 'On Watch'), ('onhold', 'On Hold'), ('update', 'Update'), ('ontrack', 'On Track')], default='offtrack', max_length=20, null=True),
        ),
    ]
