# Generated by Django 2.2.3 on 2019-07-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190718_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectnumber',
            field=models.IntegerField(unique=True),
        ),
    ]
