# Generated by Django 2.2.3 on 2019-08-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190815_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='electricalengineer',
            field=models.CharField(default='Not Entered', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mechanicalengineer',
            field=models.CharField(default='Not Entered', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='programmer',
            field=models.CharField(default='Not Entered', max_length=20, null=True),
        ),
    ]
