# Generated by Django 2.1.4 on 2019-02-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_initialproject_pastproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastproject',
            name='employees',
        ),
        migrations.AddField(
            model_name='project',
            name='assemblycomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='customerrunoffcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='documentationcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='eereleasecomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='finishingcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='installfinishcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='installstartcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='integrationcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='internalrunoffcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='manufacturingcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='mereleasecomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='shipcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PastProject',
        ),
    ]
