# Generated by Django 2.2.3 on 2019-09-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190825_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Slippage',
            field=models.IntegerField(default=0),
        ),
    ]
