# Generated by Django 2.1.4 on 2019-02-07 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190206_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='eereleasecomplete',
            new_name='electricalreleasecomplete',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='mereleasecomplete',
            new_name='mechanicalreleasecomplete',
        ),
    ]
