# Generated by Django 2.1.4 on 2019-02-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190206_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assembly',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='customerrunoff',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='documentation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='electricalrelease',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='finishing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='installfinish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='installstart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='integration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='internalrunoff',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='iscurrent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manufacturing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mechanicalrelease',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='offtrack',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='onwatch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ship',
            field=models.DateField(blank=True, null=True),
        ),
    ]
