# Generated by Django 2.1.4 on 2019-02-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190206_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='iscurrent',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='offtrack',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='onwatch',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
