# Generated by Django 2.2.3 on 2019-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190921_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='Mechanical_Release_Complete',
            field=models.BooleanField(default=False),
        ),
    ]
