# Generated by Django 2.2.3 on 2019-10-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20191017_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='scheduled',
            new_name='Assembly_Scheduled',
        ),
        migrations.AddField(
            model_name='project',
            name='Customer_Runoff_Scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Documentation_Scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Electrical_Release_Scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Finishing_Scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Install_FinishSchedulede',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Install_Start_Scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Internal_Runoff_Scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Manufacturing_Scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Mechanical_Release_Scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Ship_Scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
