# Generated by Django 2.1.4 on 2019-02-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190221_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='engineering_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
