# Generated by Django 2.2.3 on 2019-11-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20191027_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Install_FinishSchedulede',
            new_name='Install_Scheduled',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Install_Start_Scheduled',
        ),
    ]
