# Generated by Django 2.1.4 on 2019-02-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_engineering_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='customerrunoff',
            new_name='customer_runoff',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='electricalrelease',
            new_name='electrical_release',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='installfinish',
            new_name='install_finish',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='installstart',
            new_name='install_start',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='internalrunoff',
            new_name='internal_runoff',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='mechanicalrelease',
            new_name='mechanical_release',
        ),
    ]
