# Generated by Django 2.2.3 on 2020-04-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20191103_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Mechanical_Release',
            new_name='Milestone_1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Mechanical_Release_Complete',
            new_name='Milestone_1_Complete',
        ),
    ]
