# Generated by Django 2.2.3 on 2020-04-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200401_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialproject',
            old_name='Mechanical_Release',
            new_name='Milestone_1',
        ),
        migrations.AlterField(
            model_name='project',
            name='Milestone_1',
            field=models.DateField(blank=True, null=True, verbose_name='Milestone 1'),
        ),
    ]
