# Generated by Django 2.2.3 on 2020-04-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200401_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialproject',
            old_name='Assembly',
            new_name='MilestoneFive',
        ),
        migrations.RenameField(
            model_name='initialproject',
            old_name='Customer_Runoff',
            new_name='MilestoneFour',
        ),
        migrations.RenameField(
            model_name='initialproject',
            old_name='Documentation',
            new_name='MilestoneSeven',
        ),
        migrations.RenameField(
            model_name='initialproject',
            old_name='Electrical_Release',
            new_name='MilestoneSix',
        ),
        migrations.RenameField(
            model_name='initialproject',
            old_name='Finishing',
            new_name='MilestoneThree',
        ),
        migrations.RenameField(
            model_name='initialproject',
            old_name='Install_Finish',
            new_name='MilestoneTwo',
        ),
        migrations.RemoveField(
            model_name='initialproject',
            name='Install_Start',
        ),
        migrations.RemoveField(
            model_name='initialproject',
            name='Integration',
        ),
        migrations.RemoveField(
            model_name='initialproject',
            name='Internal_Runoff',
        ),
        migrations.RemoveField(
            model_name='initialproject',
            name='Manufacturing',
        ),
        migrations.RemoveField(
            model_name='initialproject',
            name='Ship',
        ),
    ]
